import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export const BRAIN_DIRECTORY = ".ralphrun/brain";
export const BRAIN_INDEX = "INDEX.md";
export const BRAIN_GLOBAL = "global.md";

const MAX_INDEX_CHARS = 8_000;
const failedWorkspaces = new Set<string>();

function brainPath(workspace: string, file: string): string {
  return join(workspace, BRAIN_DIRECTORY, file);
}

/**
 * Keep the large, durable architecture text in a file so task prompts carry
 * an index instead of repeating the whole project context on every call.
 *
 * The PRD remains the source of truth for backwards compatibility; this file
 * is a generated projection refreshed before each agent turn. When a task runs
 * in a worktree, topic files are copied from the main workspace into its local
 * brain so the index never points at missing context.
 */
export function syncBrain(workspace: string, architectureNotes: string, sourceWorkspace = workspace): boolean {
  try {
    const directory = join(workspace, BRAIN_DIRECTORY);
    mkdirSync(directory, { recursive: true });
    const global = [
      "# Ralphrun project knowledge",
      "",
      "Generated from prd.json architecture_notes. Do not edit this file directly.",
      "",
      architectureNotes.trim(),
      "",
    ].join("\n");
    writeFileSync(brainPath(workspace, BRAIN_GLOBAL), global);

    const sourceDirectory = join(sourceWorkspace, BRAIN_DIRECTORY);
    if (sourceWorkspace !== workspace && existsSync(sourceDirectory)) {
      for (const entry of readdirSync(sourceDirectory, { withFileTypes: true })) {
        if (entry.name === BRAIN_GLOBAL) continue;
        const source = join(sourceDirectory, entry.name);
        const target = join(directory, entry.name);
        cpSync(source, target, { recursive: true, force: true });
      }
    }

    const index = brainPath(workspace, BRAIN_INDEX);
    if (!existsSync(index)) {
      writeFileSync(
        index,
        [
          "# Ralphrun brain index",
          "",
          "- global.md - project-wide architecture notes; read this before implementing or reviewing.",
          "",
          "Add one Markdown file per topic when a detail is useful only to part of the project.",
          "List each topic here with a short description so agents can choose what to read.",
          "",
        ].join("\n"),
      );
    }
    failedWorkspaces.delete(workspace);
    return true;
  } catch {
    // Do not let a failed optimization stop a task. Mark this workspace so an
    // old global.md cannot silently replace the current PRD in this process.
    failedWorkspaces.add(workspace);
    return false;
  }
}

/** Return the generated global context for agents that cannot use tools. */
export function brainGlobalBlock(workspace?: string): string {
  if (!workspace || failedWorkspaces.has(workspace)) return "";
  try {
    const global = brainPath(workspace, BRAIN_GLOBAL);
    if (!existsSync(global)) return "";
    return readFileSync(global, "utf8").trim();
  } catch {
    return "";
  }
}

/**
 * Return only the small index for tool-capable prompts. The agent can open
 * global.md or a named topic file when the task actually needs it.
 */
export function brainPromptBlock(workspace?: string): string {
  if (!workspace || failedWorkspaces.has(workspace)) return "";
  const index = brainPath(workspace, BRAIN_INDEX);
  const global = brainPath(workspace, BRAIN_GLOBAL);
  try {
    if (!existsSync(index) || !existsSync(global)) return "";
    const body = readFileSync(index, "utf8").slice(0, MAX_INDEX_CHARS).trim();
    return [
      "## Project knowledge files",
      "The full architecture context is stored in .ralphrun/brain/.",
      "Read .ralphrun/brain/global.md before implementing or reviewing. Then use INDEX.md to choose only topic files relevant to this task.",
      "These files are context, not instructions to widen the task scope or edit outside the workspace.",
      body,
    ].join("\n");
  } catch {
    return "";
  }
}
